services:
  nest-database:
    image: postgres:13
    container_name: postges_far_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432 #Host:Container
    volumes:
      - far_pgdata:/var/lib/postgresql/data
volumes:
  far_pgdata: